language: python
sudo: false
arch:
 - ppc64le
addons:
  postgresql: "9.4"
before_script:
 - ln -s /tmp/.s.PGSQL.5432 /var/run/postgresql/.s.PGSQL.5432
 - "psql -c 'create database psycopg2_test;' -U postgres"
 - "psql psycopg2_test -c 'create extension hstore;' -U postgres"
env:
 - PSYCOPG2_TESTDB_USER=postgres
install: python setup.py install
script: python setup.py test
after_script:
  - "psql -c 'create database psycopg2_cffi_test_db;' -U postgres"
  - git clone https://github.com/chtd/psycopg2-benchmarks.git --depth 1
  - pip install -r psycopg2-benchmarks/django_bench/requirements.txt
  - cd psycopg2-benchmarks/django_bench/ && ./bench 1000 5
matrix:
  fast_finish: true
  include:
    - python: 3.8
      dist: xenial
      sudo: true
